Introduce tap on back of the smartphone gesture recognition
mjakobczyk/calculator-android pull request #1
Opened 2020-04-02 19:18 UTC by dist3r

2020-04-02 20:27 UTC, mjakobczyk requested changes
Just minor changes. Application has been succesfully built and ran.

2020-04-02 20:27 UTC, mjakobczyk commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +        Log.d(TAG, "Tap recognized!");
It could be a constant.

2020-04-02 20:27 UTC, mjakobczyk commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +        double zAxisAcceleration = event.values[2];
Could event be null and contain no values then?

2020-04-02 20:27 UTC, mjakobczyk commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +    private void onTapRecognized() {
This method definition should be placed after `onSensorChanged` method definition for better readability.

2020-04-02 20:27 UTC, mjakobczyk commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +    private static final long TAP_INTERVAL = 250000000;
It would be helpful to state what is the unit of this value.

2020-04-02 20:27 UTC, mjakobczyk commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +    public void onAccuracyChanged(Sensor sensor, int accuracy) {}
Please make these parameters final.

2020-04-02 20:27 UTC, mjakobczyk commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +    public void onSensorChanged(SensorEvent event) {
Please make these parameter final.

2020-04-02 21:16 UTC, dist3r commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +        double zAxisAcceleration = event.values[2];
I think there is no such a possibility. At least I haven't found any information about it, even in the official reference: https://developer.android.com/reference/android/hardware/SensorEventListener#onSensorChanged(android.hardware.SensorEvent)

2020-04-02 21:17 UTC, dist3r commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +    public void onSensorChanged(SensorEvent event) {
Done

2020-04-02 21:17 UTC, dist3r commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +    public void onAccuracyChanged(Sensor sensor, int accuracy) {}
Done

2020-04-02 21:17 UTC, dist3r commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +    private void onTapRecognized() {
Done

2020-04-02 21:23 UTC, dist3r commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +    private static final long TAP_INTERVAL = 250000000;
Done (only for interval since there is no good abbreviation for meters per second squared)

2020-04-02 21:38 UTC, dist3r commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +        Log.d(TAG, "Tap recognized!");
I'm not sure if it's needed here, basically I agree with [this](https://stackoverflow.com/a/41541685/6194055) statement. But please correct me if there are some better reasons to do that and I will change the code

2020-04-03 08:16 UTC, mjakobczyk commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +        double zAxisAcceleration = event.values[2];
Okay, let's leave it this way then.

2020-04-03 08:17 UTC, mjakobczyk commented on app/src/main/java/com/example/adaptedcalculator/MainActivity.java
> +        Log.d(TAG, "Tap recognized!");
We could define logging constants in another module to keep them all in one place and reuse them. In this case we would not pay much attention to these constants, so let's leave it as it is.

2020-04-03 08:18 UTC, mjakobczyk approved these changes

2020-04-03 08:18 UTC, merged